name: Test

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm test
      - name: Archive code coverage results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: test/coverage/
      - name: Release Dry Run
        run: npx commit-and-tag-version --dry-run
      - name: Archive test results on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test/test-results/
